### ISSUE TITLE
problem in webpack environment

### ISSUE THREAD

**Issue by geohuz** [bokuweb/react-resizable-and-movable#12]
ERROR in ./~/react-resizable-and-movable/~/react-resizable-box/lib/index.js
Module parse failed: /Users/geohu/Codings/Web_front/hingeOrgChart/node_modules/react-resizable-and-movable/node_modules/react-resizable-box/lib/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React, { Component, PropTypes } from 'react';
| import assign from 'react/lib/Object.assign';
| import Resizer from './resizer';
 @ ./~/react-resizable-and-movable/lib/index.js 17:25-55

**Comment by bokuweb** [comment]
thx
please try react-resizable-and-movable@0.1.5
