### ISSUE TITLE
Resizing does not lock moving

### ISSUE THREAD

**Issue by bdyetton** [bokuweb/react-resizable-and-movable#18]
Great component thanks!
However, when i place in in my app, every time I resize the box moves too. This does not happen in you demo. Any ideas why?
Also, is there a way to stop the resize arrow from appearing on the y axis?
Thanks!

**Comment by bokuweb** [comment]
Thank you very much. We will investigate.
Also, please tell me your piece of code

**Comment by bdyetton** [comment]
Thanks:
Here is the relevant component code that constructs and renders the  'DragBox' which is your 'resizeable-and-moveable-box' 
```
    addMarker: function(e) {
      var self = this;
      if (e.button !== 0) return;
      var scoreImg = $(this.refs.sigImg);
      var newMarker = <DragBox
          key={self.state.markerIndex}
          index={self.state.markerIndex}
          start={{x: e.pageX-scoreImg.offset().left, y: 0, width: 200, height: scoreImg.height()}}
          customStyle={{background:"#333", opacity: 0.7, textAlign:"center", paddingTop: '20px', border:'1px solid #0d0'}}
          />;
      var markers = self.state.markers;
      markers[self.state.markerIndex]=newMarker;
      this.setState({
          markers: markers,
          markerIndex: self.state.markerIndex+1
      });
    },

    render: function () {
        var self = this;
        var markers = $.map(this.state.markers, function(value, index) {
            return [value];
        });
        return (
            <div><p>Now logged in as {self.props.user}</p><p>Epoch ID: {self.state.currentRemImage}</p>
            <div style={{position:'relative'}}>
                {markers}
                <img ref='sigImg' src={window.location.href + (self.state.currentRemImage)} alt='remImage' onClick={this.addMarker} pointer-events='none'></img>
            </div>
            <input ref='previous' type='button' onClick={self.getPreviousRemImage } value='Previous Epoch'></input>
            <input ref='next' type='button' onClick={self.getNextRemImage} value='Next Epoch'></input>
            <p>{self.state.msg == 'ok' ? '' : self.state.msg}</p>
            </div>
        );
    }
```

I believe the problem is that that the ```disabled``` property of the Draggable component is not working properly.

**Comment by bdyetton** [comment]
I think maybe the Draggable Component gets the click event before the react-resizable-and-movable component, and so the ```disabled``` state change for the Draggable object comes to late?

**Comment by bokuweb** [comment]
Hmmmm... If you place simpleset component, is it working properly?

```
    render: function () {
      <DragBox
          start={{x: 0, y: 0, width: 200, height: 200}}
          customStyle={{background:"#333", opacity: 0.7, textAlign:"center", paddingTop: '20px', border:'1px solid #0d0'}} />;
        );
    }
```

> Also, is there a way to stop the resize arrow from appearing on the y axis?

I'm going to append `isResazable{x:boolean, y:boolean, xy:boolean}` property.

**Comment by bdyetton** [comment]
Thanks for replying so swiftly.
No that still has the same issue. Strangely, if i call the following inside the react-resizable-and-movable component:
```javascript
  componentDidMount(){
    this.onResizeStart()
  }
```
Then for the first resize it works great, but then after moving it once the problem comes back. Again, this makes me think its something to do with the event propagation because the ```disabled``` works when called without an event (as in the code above), but doesn't work when an actual event is triggered.

Ah nice, i see the ```isResizable{x:boolean, y:boolean, xy:boolean}``` is a property of your react-resizable-box class. I set that internally in the render function of react-resizable-and-movable and it stopped the y resizing.

**Comment by bokuweb** [comment]
Please try v0.2.4
Add `isResizable` option and `stopPropagation` when resizestart.

sorry, not be reproduced on my env...

**Comment by bdyetton** [comment]
Thanks, but i get the following error:
```javascript
Uncaught TypeError: Cannot read property 'stopPropagation' of undefined
```
I don't think the event makes it to the resizeStart function (potentially because it its consumed by the Draggable object? Im not really that familiar with event propagation).

Also, I think it would be usefully to break out the 'axis' prop of the Draggable, thereby allowing moving on only one axis. 
Thanks for your help!

**Comment by bokuweb** [comment]
Hmmmm... Please check following list

- what is `react-resizable-box` version, if not v0.1.7, update it.
- what is stored in `onResizeStart` 1st argument. (I want to know why `'stopPropagation' of undefined` occured)

If you can, please send me the project which is minimized in order to reproduce.

**Comment by bdyetton** [comment]
- Yep, i updated, but no effect.
- the second arg (```e```) is undefined. The first arg ```dir``` is 'x' or 'y' depending on the direction (as per the readme)

Ill make a version of the project available soon to help reproduce.

**Comment by bokuweb** [comment]
>the second arg (e) is undefined. The first arg dir is 'x' or 'y' depending on the direction (as per the readme)

- react-resizable-box version is 0.1.7?

> Ill make a version of the project available soon to help reproduce.

thunks

**Comment by bdyetton** [comment]
Well in creating a version of the project for you to reproduce the error, i ended up fixing it!
Im still not 100% on what the error was, but i believe that i had this react [draggable](https://github.com/mzabriskie/react-draggable) as well as your version in my node packages, and the incorrect draggable component was being created. Could have been something else also...
Thanks for your support!

As a feature request, would you mind adding control of the axis property of the draggable component to the resizeable-and-moveable component?
Or maybe i can make a pull request? I'm not super familiar with how to do that though :)

**Comment by bokuweb** [comment]
:+1: 

> As a feature request, would you mind adding control of the axis property of the draggable component to the resizeable-and-moveable component?

Welcome your PR. If you can not,  I'll do it if Moraere wait a little.
