### ISSUE TITLE
Resize on left and top edge

### ISSUE THREAD

**Issue by bdyetton** [bokuweb/react-resizable-and-movable#23]
Hi Bokuweb, 
I would like to be able to resize by clicking and dragging on the left (and top) edges.
Are there any plans to allow for this?

**Comment by bokuweb** [comment]
Hi @bdyetton 
It's not the plan for now. I'm sorry.

**Comment by bdyetton** [comment]
Ok cool. Maybe Ill have a go adding it myself then

**Comment by bokuweb** [comment]
@bdyetton implement left and top resizer, please see demo.

**Comment by bdyetton** [comment]
Awesome thanks!!!
