### ISSUE TITLE
How to prevent click on drag and resize?

### ISSUE THREAD

**Issue by tastemeru** [bokuweb/react-resizable-and-movable#25]
How to prevent event `onClick`, when I'm dragging?
Will be really glad for answer, it goes me crazy, Thanks!

**Comment by bokuweb** [comment]
@tastemeru Hi. If you do not mind, please show me the code of part of ResizableAndMovable component.

**Comment by tastemeru** [comment]
Sorry, can't show the "production" version, because I broke there everything, but here is an example:
```
        return <ResizableAndMovable
                start={{x: this.props.dot.x, y: this.props.dot.y, height: this.props.dot.h, width: this.props.dot.w}}
                onDragStop={ () => { console.log('onDragStop'); } }
                onDrag={ () => { console.log('onDrag'); } }
                onClick={ () => { console.log('onClick'); } }
                bounds={'parent'}
                customClass={'dot'}
                >
        </ResizableAndMovable>
```
And as a result: https://monosnap.com/file/euLXzSGa0RPRFyZZJFaLQmZrT7jNnU
The problem is that after `onDrag` we have `onClick` event.  I'm trying to develop a modal toggle on click and as a result I get toggle after `onDrag` event(https://monosnap.com/file/DSJqpnne2RbAwvjp14shUwyEQh9VX3). I tried to play with local states, kinda set to true during the dragging and then check it before create modal, but it seems as `onClick` event start before `onDragStart` and finish after `onDrag`. Sorry for bothering you, but I really broke my head with this stuff. And a funny fact, that jQuery draggable works fine, but I think it's the bad choice for react. Thanks!

**Comment by bokuweb** [comment]
@tastemeru thanks.We'll investigate, please give your time a little

**Comment by tastemeru** [comment]
Currently fix it with this plug:
http://stackoverflow.com/questions/6042202/how-to-distinguish-mouse-click-and-drag
Set the onMouse events on a children div and it works.

**Comment by tastemeru** [comment]
But it seems as not really elegant solution, if you have any suggestions, I'll be glad to hear, thanks!

**Comment by bokuweb** [comment]
@tastemeru thanks!! I'll consider continously.

**Comment by dengnan123** [comment]
Solve it ？

**Comment by vercamach** [comment]
Still not solved?

**Comment by theDoinb** [comment]
I try to solve：

onDrag ：{   this.isDragged = true;  }

onDragStop ：{  if( this.isDragged){  ..execute sth }；  this.isDragged = false}
