### ISSUE TITLE
Why doesn't setState effect component's position?

### ISSUE THREAD

**Issue by varandpez** [bokuweb/react-resizable-and-movable#30]
Hi,

For x, y and width I'm using component's state. That is because the state of the component can be fetched for recovery and things like that. but it seems like "ResizableAndMovable" does not handle reRendering of the component.

Any advice?

Thanks.

**Comment by bokuweb** [comment]
@varandpez Hi. thanks for your report.
it's a Known Issue..

`react-resizable-and-movable` use `react-draggable`. but  `react-draggable` can not update position by parent component.

I'm going to fix this issue.
Please give me a little more time.

**Comment by varandpez** [comment]
With a small trick I was able to bypass this issue, but definitely would be better to do it the right way.
I added "key" attribute to the component state with random() value on setState, so that react re render the component because of key change.

**Comment by bokuweb** [comment]
@varandpez 

thanks for your report.I'm going to fix this issue.

**Comment by bokuweb** [comment]
@varandpez 

Update component. please use v1.0.0.
Remove start props, and please use width, height, x, y props

**Comment by varandpez** [comment]
👍  Tnx
