### ISSUE TITLE
why cannot specify a drag handle？

### ISSUE THREAD

**Issue by adolli** [bokuweb/react-resizable-and-movable#31]
Hi, 

it is very cool to use your react-resizable-and-movable. but i meet some problems with my content that i need select some text of the movable panel. in this case, when i try to select the text, the panel moves. is there a way to set drag handle like react-draggable?

Thanks.

**Comment by bokuweb** [comment]
@adolli thanks for your report.
This component use customized  `react-draggable`.
So, It is possible to pass drag handle props to  `react-draggable`, which is child of `react-resizable-movable`.
I'm going to implement this props next version.

thanks.

**Comment by adolli** [comment]
thank u very much for your reply so quick. i'm going to upgrade all my `react-draggable` to `react-resizable-movable`

**Comment by adolli** [comment]
i'm sorry to trouble u again.
when will next version be available? in current latest version, it still takes no effect by passing props like `handle='.drag-handle'`.

Thanks

**Comment by bokuweb** [comment]
@adolli  sorry, I dont implemet it yet, I 'm going to implement it as soon as possible

**Comment by bokuweb** [comment]
@adolli FIxed. Please try vr 0.5.3. but v0.5.3 not support v15.0 yet.
