### ISSUE TITLE
onChange prop

### ISSUE THREAD

**Issue by agentcooper** [bokuweb/react-resizable-and-movable#44]
Does it make sense to suggest an additional prop `onChange: (updatedPosition: { x, y, width, height }) => void`? It will call the passed callback when any change did happen (resize or drag) with the updated coords and dimensions.

**Comment by bokuweb** [comment]
@agentcooper Thank you for proposal. it is simple and nice idea. Now, certainly call back is too much. But, even if add `onChange` callback, `onResize` and `onDrag` is required, and they are overlapping.I want to add if to reduce the callbacks.
