### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by kudlajz** [bokuweb/react-resizable-and-movable#47]
Hi,

I'd like to use your component as it is exactly what I'm looking for, but unforunately, I get a following error:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "react-resizable-and-movable"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 no such package available : @bokuweb/react-draggable-custom
npm ERR! 404 
npm ERR! 404  '@bokuweb/react-draggable-custom' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-resizable-and-movable'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Is there a problem with my system or is this a global problem? I haven't found anyone dealing with the same issue.

**Comment by alicebob** [comment]
Same problem here with a clean install. @bokuweb, could you add that package?

**Comment by bokuweb** [comment]
Ummmm, I can't reproduce the error....

```
node -v v6.2.2
npm  -v 3.9.5
```

**Comment by kudlajz** [comment]
@bokuweb Do you have a repository called `@bokuweb` set by any chance?

**Comment by bokuweb** [comment]
@kudlajz no.it is not set.

my `~/.npmrc` is only set `registry.npmjs.org/:_authoken=xxxxxxxxxxxxxxxxx`



![2016-08-31 21 27 42](https://cloud.githubusercontent.com/assets/10220449/18128640/cdd07c08-6fc1-11e6-856f-7e389f9309e8.png)

**Comment by bokuweb** [comment]
Similar case?

https://github.com/rlidwka/sinopia/issues/399

**Comment by kudlajz** [comment]
@bokuweb Yep, it worked. Thanks!

```npm config set "@bokuweb:registry" http://registry.npmjs.org/```

**Comment by bokuweb** [comment]
@kudlajz oh!!thanks!!

**Comment by alicebob** [comment]
upgrading npm and / or the `npm config` from above fixed it for me.

from:
node -v v4.3.1
npm -v 1.4.21
to:
v6.5.0
v3.10.3

(debian testing has those old versions available)

Thanks for the help!

**Comment by bokuweb** [comment]
@alicebob thanks!!
